[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.polybar]
input_path = './templates/polybar-colors.ini'
output_path = '~/.config/polybar/colors.ini'

[templates.i3]
input_path = './templates/i3-colors.conf'
output_path = '~/.config/i3/colors.conf'

[templates.sway]
input_path = './templates/i3-colors.conf'
output_path = '~/.config/sway/colors.conf'

[templates.scroll]
input_path = './templates/i3-colors.conf'
output_path = '~/.config/scroll/colors.conf'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.waybar]
input_path = './templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
